version: '3.8'

services:
  web:
    image: prework-flask-app:latest
    build: .
    expose:
      - "5000"
    depends_on:
      - redis
    env_file:
      - .env
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "5001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

volumes:
  redis_data:

networks:
  webnet:
